version: "3.9"
networks:
  localdev:
services:
  sample:
    build: .
    environment:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "${APP_TCP_PORT:-5080}:5080"
    networks:
      - localdev
